#builders:
#  build_native:
#    auto_apply: all_packages
#    import: "package:build_native/build_native.dart"
#    builder_factories:
#      - cmakeBuilder
#    build_extensions:
#      .build_native.yaml:
#        - .build_native.so
#        - .build_native.dylib
#        - .build_native.dll
#        - .build_native.cmake
builders:
  object_file:
    auto_apply: all_packages
    import: "package:build_native/build_native.dart"
    builder_factories:
      - objectFileBuilder
    runs_before:
      - "build_native|library"
    build_extensions: { '.c': ['.o', '.obj'], '.cc': ['.o', '.obj'], '.cpp': ['.o', '.obj'] }
  library:
    auto_apply: all_packages
    import: "package:build_native/build_native.dart"
    builder_factories:
      - libraryBuilder
    build_extensions: { '.build_native.yaml': ['.so', '.dylib', '.dll'] }