builders:
  build_native:
    auto_apply: all_packages
    import: "package:build_native/build_native.dart"
    builder_factories:
      - cmakeBuilder
    build_extensions:
      .build_native.yaml:
        - .build_native.so
        - .build_native.dylib
        - .build_native.dll
        - .build_native.txt