author: Tobe O <thosakwe@gmail.com>
description: Compile native extensions with package:build, using the system compilers.
homepage: https://github.com/thosakwe/build_native
name: build_native
version: 0.0.11+1
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  args: ^1.0.0
  archive: ^2.0.0
  build: ^1.0.0
  build_config: ^0.3.0
  cli_util: ^0.1.3
  collection: ^1.0.0
  convert: ^2.0.0
  crypto: ^2.0.0
  front_end: ^0.1.2
  io: ^0.3.0
  lzma: ^0.4.0
  path: ^1.0.0
  recase: ^2.0.0
  scratch_space: ^0.0.3
  source_span: ^1.0.0
  system_info: ^0.1.0
  quiver: ^2.0.0
  yaml: ^2.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
executables:
  build_native: build_native
