author: Tobe O <thosakwe@gmail.com>
description: Compile native extensions with package:build.
homepage: https://github.com/thosakwe/build_native
name: build_native
version: 0.0.0
environment:
  sdk: ">=1.19.0"
dependencies:
  build: ^0.9.0
  path: ^1.0.0
