author: Tobe O <thosakwe@gmail.com>
description: Compile native extensions with package:build.
homepage: https://github.com/thosakwe/build_native
name: build_native
version: 0.0.1
environment:
  sdk: ">=1.19.0 <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  build: ^0.12.0
  build_config: ^0.2.0
  cli_util: ^0.1.3
  collection: ^1.0.0
  package_resolver: ^1.0.0
  path: ^1.0.0
  system_info: ^0.0.6
  yaml: ^2.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^0.8.0
